---
title: "Individual1 Lab 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### First Push code.  This is just for setting up the Repository. 

```{r}
#install.packages("devtools")
#devtools::install_github("hadley/productplots")

``` 


```{r}
data(happy, package = "productplots")
head(happy)
```


```{r}
HAPPY <- readRDS("HAPPY.rds")
head(HAPPY, 5)
# Info about  variables, gathered from the gssdata website.
# HAPPY - General happiness.   (All years available)
# YEAR - Gss year for this respondent.   (All years available)
# AGE - Age of the respondent. (All years available)
# SEX - Respondents sex (All years available)
# MARITAL - Marital status (All years available)
# DEGREE - Respondents highest degree   (All years available)
# FINRELA - Opinion of family income   (All years available)
# HEALTH - Condition of health   (Available 28 of 31 years recorded)
# WTSSALL - Weight of variables   (Available 17 of the 31 years recorded )


# [[[PARTYID]]] - Political party affiliation   (All years Available )

# [[[POLVIEWS]]] - Think of self as liberal or conservative   ( Available 29 of 31 years)
``` 

```{r}
class(HAPPY) # Is a data.fraem
str(HAPPY)
head(HAPPY, 20)
tail(HAPPY, 20)

### Things to note from the start
# HAPPY (Character)
# YEAR (Integer)
# AGE (Character) - seems a little weird
# SEX (Character)
# MARITAL (Character)
# DEGREE (Character)
# FINRELA (character)
# HEALTH (character)
# WTSSALL (numeric)
# PARTYID (character)
# POLVIEWS (Character)



dim(HAPPY)  #62466 Rows and 11 Columns
#HAPPY data.frame is in long format
names(HAPPY)

summary(HAPPY)



```

PART 1 #1
```{r}

table(HAPPY$HAPPY)  #CHECK
table(HAPPY$YEAR)   #CHECK
table(HAPPY$AGE)    #DETECTED  (DK)
table(HAPPY$SEX)    #CHECKED
table(HAPPY$MARITAL)  # CHECKED
table(HAPPY$DEGREE)   # DETECTED (DK)
table(HAPPY$FINRELA)  # DETECTED (DK)
table(HAPPY$HEALTH)   # DETECTED(DK, IAP)
#table(HAPPY$WTSSALL)  # CHECKED
table(HAPPY$PARTYID)   # DETECTED (DK)
table(HAPPY$POLVIEWS)   # DETECTED (DK, IAP)

# No "NA" values were detected.  This was verified above and also by viewing the global enviroment uisng the search bar. 

```

```{r}

HAPPY[HAPPY == "DK"] <- NA
HAPPY[HAPPY == "IAP"] <- NA
HAPPY[HAPPY == "NA"] <- NA  



#Replace all of the indcated values with NA
```


```{r}

library(dplyr)

head(HAPPY, 20)
tail(HAPPY, 20)

```
#PART 1 #2
```{r}
#is.XXX checks for specific type
#as.XXX casts to specific type


HAPPY$AGE[HAPPY$AGE == "89 OR OLDER"] <- "89"
HAPPY <- HAPPY %>% mutate(HAPPY = factor(HAPPY), AGE = as.numeric(AGE), SEX = factor(SEX), MARITAL = factor(MARITAL), DEGREE = factor(DEGREE), FINRELA = factor(FINRELA), HEALTH = factor(HEALTH), PARTYID = factor(PARTYID), POLVIEWS = factor(POLVIEWS))

str(HAPPY)
head(HAPPY, 20)
tail(HAPPY, 20)

```

# PART 1 #3 
```{r}

sum(summary(HAPPY$MARITAL))

#HAPPY_MARI_INFO <- HAPPY %>% group_by(MARITAL) %>% summarize(mean_rate_each_level = mean(AGE, na.rm = TRUE))

#HAPPY_MARI_INFO # We see that based on average age, a sensible order would be "NEVER MARRIED", "SEPARATED", "MARRIED", "DIVORCED", and "WIDOWED"

lvl_MARITAL_COL <- c("NEVER MARRIED", "SEPARATED", "MARRIED", "DIVORCED", "WIDOWED")
HAPPY <- HAPPY %>% mutate(MARITAL = factor(MARITAL, lvl_MARITAL_COL))

HAPPY %>% group_by(MARITAL) %>% summarize(n = n(), mean_age = mean(AGE, na.rm = TRUE)) %>% arrange((mean_age))
levels(HAPPY$MARITAL)

```

```{r}

lvl_HAPPY_COL <- c("NOT TOO HAPPY", "PRETTY HAPPY", "VERY HAPPY")
HAPPY <- HAPPY %>% mutate(HAPPY = factor(HAPPY, lvl_HAPPY_COL))
levels(HAPPY$HAPPY)

```

```{r}

lvl_DEGREE_COL <- c("LT HIGH SCHOOL", "HIGH SCHOOL", "BACHELOR", "GRADUATE")
HAPPY <- HAPPY %>% mutate(DEGREE = factor(DEGREE, lvl_DEGREE_COL))
levels(HAPPY$DEGREE)

```

```{r}

lvl_HEALTH_COL <- c("POOR", "FAIR", "GOOD", "EXCELLENT")
HAPPY <- HAPPY %>% mutate(HEALTH = factor(HEALTH, lvl_HEALTH_COL))
levels(HAPPY$HEALTH)

```

```{r}

lvl_FINRELA_COL <- c("FAR BELOW AVERAGE", "BELOW AVERAGE", "AVERAGE", "ABOVE AVERAGE", "FAR ABOVE AVERAGE")
HAPPY <- HAPPY %>% mutate(FINRELA = factor(FINRELA, lvl_FINRELA_COL))
levels(HAPPY$FINRELA)
```


